-- Migration: Remove categories from transactions
-- Purpose: Simplify data model - AI auto-reasons keterangan instead of using categories
-- Date: 2026-03-26

-- Step 1: Drop foreign key constraint on category_id
ALTER TABLE transactions 
DROP CONSTRAINT IF EXISTS transactions_category_id_fkey;

-- Step 2: Drop category_id column from transactions
ALTER TABLE transactions 
DROP COLUMN IF EXISTS category_id;

-- Step 3: Drop index on category_id (if exists)
DROP INDEX IF EXISTS transactions_category_id_idx;

-- Step 4: Optionally drop categories table entirely
-- Uncomment if you want to remove categories completely:
-- DROP TABLE IF EXISTS categories;

-- Note: We keep the categories table for backward compatibility
-- but it's no longer used in the transaction flow.
-- You can manually drop it later if needed.

-- Step 5: Add comment to document the change
COMMENT ON COLUMN transactions.type IS 'Transaction type: income (pemasukan) or expense (pengeluaran)';
COMMENT ON COLUMN transactions.description IS 'Auto-generated by AI from user chat (e.g., "Gaji bulanan", "Beli makan siang")';

-- Verify the changes
-- SELECT column_name, data_type, is_nullable 
-- FROM information_schema.columns 
-- WHERE table_name = 'transactions' 
-- ORDER BY ordinal_position;
